[phases.setup]
nixPkgs = ["python39", "postgresql"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["python init_db.py"]

[start]
cmd = "uvicorn api:app --host 0.0.0.0 --port $PORT"
